import type { Metadata } from "next";

import localFont from "next/font/local"
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Box, Container } from "@mui/material";


const inter = localFont({ src: "../../public/asset/fonts/Rezvan/Rezvan.ttf" });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html dir="rtl" lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <main>
            {children}
        </main>

      </body>
    </html>
  );
}
