
import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";



import localFont from "next/font/local"
import Footer from "@/components/footer/Footer";
// const inter = localFont({ src: "../../public/asset/fonts/lalezar/Lalezar-Regular.ttf" });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


      <html dir="rtl" lang="fa">
        <body>
          <header>
            <Navbar />
          </header>

          <main>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
  );
}
